ARG PYTHON_VERSION=3

FROM python:${PYTHON_VERSION}

MAINTAINER Daniel M. Kwon <daniel.minseok.kwon@gmail.com>

RUN mkdir /src
WORKDIR /src

COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /src

# CMD [ "python", "./your-daemon-or-script.py" ]